apiVersion: v1
kind: Service
metadata:
  name: webserver-php-svc
  labels:
    type: webserver-php
spec:
  selector:
    type: webserver-php
  type: NodePort
  ports:
  - nodePort: 30002
    port: 80
    targetPort: 80
    name: webserver-php-port