apiVersion: v1
kind: Service
metadata:
  name: webserver-html-svc
  labels:
    type: webserver-html
spec:
  selector:
    type: webserver-html
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80
    name: webserver-html-port
